name: deploy

on:
  push:
    branches:
      - main

jobs:
  staging:
    name: Deploy to staging
    runs-on: self-hosted
    environment:
      name: staging
      url: https://korekari.moonlit.works/
    outputs:
      semver: ${{ steps.version.outputs.semver }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - name: Get version
        id: version
        run: |
          echo "::set-output name=semver::$(git describe --tags | sed 's/v//')"
      - name: Set image
        id: tag
        run: |
          echo "::set-output name=bare::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}"
          echo "::set-output name=version::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ steps.version.outputs.semver }}"
      - uses: docker/login-action@v1
        name: Login to docker registry
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t ${{ steps.tag.outputs.version }} .
      - name: Push image
        run: docker image push ${{ steps.tag.outputs.bare }} --all-tags
      - name: Update deployment image
        uses: eyzi/k8s-deploy@v1
        with:
          api_url:    ${{ secrets.DEPLOY_URL }}
          api_token:  ${{ secrets.DEPLOY_TOKEN }}
          image:      ${{ steps.tag.outputs.bare }}
          version:      ${{ steps.version.outputs.semver }}

  # production:
  #   name: Deploy to production
  #   runs-on: self-hosted
  #   environment:
  #     name: production
  #     url: https://korekari.moonlit.works/
  #   needs: staging
  #   steps:
  #     - name: Update deployment image
  #       uses: eyzi/k8s-deploy@v1
  #       with:
  #         api_url: ${{ secrets.DEPLOY_URL }}
  #         api_token: ${{ secrets.DEPLOY_TOKEN }}
  #         image: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}
  #         version: ${{ needs.staging.outputs.semver }}
